import { Inter } from "next/font/google";
import "@/styles/bootstrap.css";
import "@/styles/style.css";
import "@/styles/responsive.css";
import "@/styles/font-awesome.css";
import "@/styles/owl-carousel.min.css";
import "@/styles/owl.theme.default.min.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
